name: fatiando-data-morroco-speleothem-qdm
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - pip
  - numpy
  - jupyterlab
  - matplotlib
  - xarray
  - netcdf4
  # Fatiando
  - pooch>=1.0
  - harmonica==0.7.*
  - pip:
    - git+https://github.com/compgeolab/magali
